### ISSUE TITLE
Shared content stream entry style

### ISSUE THREAD

**Issue by Semir1212** [humhub/sharebetween#28] opened 2023-03-30 15:54 UTC
![image](https://user-images.githubusercontent.com/38326726/228892334-c5409291-2cd7-4f70-b065-e6e25279d410.png)

The posts should not be visually above all other posts. They are shared, not recommended or highlighted. Highlighting them in such fashion could also conflict with future developments, which is why I would reconsider the design.

**Comment by Eladnarlea** [comment] 2023-04-03 07:04
@Semir1212 I agree, this could lead to inconveniences in future design developments. Thank you! :)

I have considered your suggestions and adjusted the designs accordingly: how do you like this: 

<img width="635" alt="Screen Shot 2023-04-03 at 8 59 42 AM" src="https://user-images.githubusercontent.com/105652258/229435616-e64089de-7b86-4efa-ae16-355a00533088.png">

**Comment by luke-** [comment] 2023-04-03 08:57
@Eladnarlea Looks good for me!


@Semir1212  Maybe we should change the text style e.g. `Emma Watson > Welcome Space · less than a minute`  should probably enough

e.g.
![image](https://user-images.githubusercontent.com/4736168/229460977-80d04713-9bfd-4a71-b0c0-83a0ca023d8b.png)

**Comment by Eladnarlea** [comment] 2023-04-03 09:55
@luke- do you suggest onmitting the '...shared a post' ? because I think it could be relevant for future developments. for instance 'Emma Watson commented'/'Emma Watson likes'...

**Comment by Semir1212** [comment] 2023-04-04 08:51
Yes @luke-

Maybe something like  "Space 1 --> Space 2 by User X * time"

I would go with an icon like this, if available: 

![image](https://user-images.githubusercontent.com/38326726/229739744-ec58ba40-02d4-403b-9baa-062dda0d22ff.png)

**Comment by Eladnarlea** [comment] 2023-04-04 09:32
@Semir1212 do I understand you correctly that you wish to see the space that the post has come from, next, where it has been shared to by whom and at what time? 

@Semir1212 @luke- Do you think that it is more important to see what space the post has originally come from first or to see the person that has shared the post?

![Screen Shot 2023-04-04 at 11 20 14 AM](https://user-images.githubusercontent.com/105652258/229749670-44b6edde-4995-4f6e-874a-9df25bb23a31.png)

![Screen Shot 2023-04-04 at 11 29 19 AM](https://user-images.githubusercontent.com/105652258/229750081-27382c37-2ebb-406a-9342-39239fdbc50b.png)

@luke- and I have agreed earlier that we think it is best to let the share module act without an icon because it could lead to an overload of the interface. (e.g. wiki, mail, tasks.... already have an icon so two icons would overstimulate the post). @Semir1212 do you agree?

**Comment by Eladnarlea** [comment] 2023-04-06 12:42
## Facebook: 
- focus on the user that has shared the post
![Screen Shot 2023-04-04 at 4 16 12 PM](https://user-images.githubusercontent.com/105652258/230381366-39af7a13-83bb-492e-8dd8-af1022bfabb0.png)
![Screen Shot 2023-04-04 at 4 13 55 PM](https://user-images.githubusercontent.com/105652258/230381449-a4922319-6f1b-4431-8af7-54aa83f1f393.png)
![Screen Shot 2023-04-04 at 4 12 04 PM](https://user-images.githubusercontent.com/105652258/230381493-cee225f8-3968-4f0c-ad8b-1e5f49852bf0.png)


## Linkedin:
- focus on author and content that has been shared (person who shared is less important)

![Screen Shot 2023-04-04 at 4 05 37 PM](https://user-images.githubusercontent.com/105652258/230381536-cb4ac09b-225c-4e77-a295-fa38292635e3.png)
![Screen Shot 2023-04-04 at 4 04 56 PM](https://user-images.githubusercontent.com/105652258/230381579-08b2c04b-7377-4bc0-acb1-2cd73be0be8a.png)
![Screen Shot 2023-04-04 at 4 07 18 PM](https://user-images.githubusercontent.com/105652258/230381674-fd838f7b-4cff-409e-8b2e-a92cc3d4bca1.png)
![Screen Shot 2023-04-04 at 4 02 54 PM](https://user-images.githubusercontent.com/105652258/230381702-1e3b4699-836c-411c-b02f-a75a291bc33e.png)

**Comment by Eladnarlea** [comment] 2023-04-06 12:52
<img width="954" alt="Screen Shot 2023-04-06 at 2 51 32 PM" src="https://user-images.githubusercontent.com/105652258/230384053-7e101f83-e249-4306-b778-829101a35276.png">

**Comment by Semir1212** [comment] 2023-04-06 12:59
Looks good. @Eladnarlea 

 Let's go with that one? @luke-

**Comment by yurabakhtin** [comment] 2023-04-20 15:14
@luke- PR https://github.com/humhub/sharebetween/pull/31:

![new-shared-style](https://user-images.githubusercontent.com/6995524/233409909-3fcff9d7-4c54-42a1-bd8b-88c178da036a.png)

**Comment by luke-** [comment] 2023-04-20 21:41
@yurabakhtin Thanks looks good. Can you please take a look into tests?

**Comment by yurabakhtin** [comment] 2023-04-21 14:14
@luke- Acceptance tests have been fixed in the commit https://github.com/humhub/sharebetween/pull/31/commits/9538da3b7cc8382c87ea70cf62bd991770ae5f40.

But we have a strange bug that I fixed in the next commit https://github.com/humhub/sharebetween/pull/31/commits/f3a83d6a87523eecbc2925e2b3dd5124e09a8f21, as you can read my comment there, by some strange reason current user is logged out automatically after insert new "Share" record, it is why I added the line to loggin the same user again.

---

Also I think this core line  https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/components/ActiveQueryContent.php#L116:

```php
$this->emulateExecution();
```

should be modified to:

```php
return $this->emulateExecution();
```

otherwise we get in the SQL query a code with empty conditions like this `'(  OR   OR  )'` when user is not logged in e.g. from the unit tests.

**Comment by luke-** [comment] 2023-04-21 18:53
@yurabakhtin Hmm, that's odd. Feel free to add the `return $this->emulateExecution()` in core. Do you want me to take a look at this or do you check the issue more detail?

**Comment by yurabakhtin** [comment] 2023-04-23 10:48
@luke- 

> Hmm, that's odd. Feel free to add the `return $this->emulateExecution()` in core. Do you want me to take a look at this or do you check the issue more detail?

The error may occurs if the method `readable()` is called for anonymous user and when guest mode is not enabled in system, but I cannot reproduce this on normal site work because when guest mode is disabled then we display only the login form, i.e the dashboard is hidden in such case where the method `readable()` is not called.
However I have decided to do the fix https://github.com/humhub/humhub/pull/6251 in order to avoid in future, because such SQL query is wrong:

![sql_or_error](https://user-images.githubusercontent.com/6995524/233835408-fd1bbd34-68da-4e20-8624-b15f903e0be4.png)

**Comment by luke-** [comment] 2023-04-23 12:13
@yurabakhtin Ok, in the tests we should always pass a user to `readable()`, expect we explicitly want to test for guests.

**Closed** 2023-04-23 12:13 UTC
Labels: enhancement
